### ISSUE TITLE
Error: ENOENT when singleVideo = false

### ISSUE THREAD

**Issue by valburyakov** [tomyam1/protractor-video-reporter#8]
protractor: 4.0.9

I run my protactror tests in docker with headless chrome browser

```
Xvfb :21 -screen 0 1920x1080x24 &
export DISPLAY=:21.0
```

When i try to run reporter with option `singleVideo = false` and after test ended successfully i get this error. 

```
E/launcher - ENOENT: no such file or directory, unlink 'test-result/videos/bee3b385-1b1f-40c3-aee2-9cc42b939bd9.mov'
E/launcher - Error: ENOENT: no such file or directory, unlink 'test-result/videos/bee3b385-1b1f-40c3-aee2-9cc42b939bd9.mov'
 at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at VideoReporter._stopScreencast (/protractor/project/node_modules/protractor-video-reporter/lib/VideoReporter.js:104:8)
    at VideoReporter.specDone (/protractor/project/node_modules/protractor-video-reporter/lib/VideoReporter.js:137:10)
    at dispatch (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1966:28)
    at ReportDispatcher.specDone (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1949:11)
    at Spec.specResultCallback [as resultCallback] (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:903:18)
    at complete (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:368:12)
    at QueueRunner.clearStack (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:660:9)
    at QueueRunner.run (/usr/lib/node_modules/protractor/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1881:12)

```

With `singleVideo = true` reporter works well but i need videos only for failed tests.

```
var videoReporter = new VideoReporter({
  baseDirectory: config.resultFolder + '/videos/',
  singleVideo: false,
  ffmpegArgs: [
    '-y',
    '-r', '30',
    '-f', 'x11grab',
    '-s', '1920x1200',
    '-i', process.env.DISPLAY,
    '-g', '300',
    '-vcodec', 'qtrle']
  });
```

**Comment by valburyakov** [comment]
I've made [PR](https://github.com/tepez/protractor-video-reporter/pull/9). The problem was in skipped spec, when video is not recorded then this error appeared in afterAll. Now it works correct.

**Comment by irtiza** [comment]
@tomyam1 

hey!

> [22:31:25] E/launcher - ENOENT: no such file or directory, unlink 'videos/Lesson 01 - Happy Path Launches Lesson 01.mov'
[22:31:25] E/launcher - Error: ENOENT: no such file or directory, unlink 'videos/Lesson 01 - Happy Path Launches Lesson 01.mov'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1089:18)
    at VideoReporter._stopScreencast (/mnt/jenkins/workspace/happy-path-branch/node_modules/protractor-video-reporter/lib/VideoReporter.js:110:10)
    at VideoReporter.specDone (/mnt/jenkins/workspace/happy-path-branch/node_modules/protractor-video-reporter/lib/VideoReporter.js:174:10)
    at dispatch (/mnt/jenkins/workspace/happy-path-branch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1966:28)
    at ReportDispatcher.specDone (/mnt/jenkins/workspace/happy-path-branch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1949:11)
    at Spec.specResultCallback [as resultCallback] (/mnt/jenkins/workspace/happy-path-branch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:903:18)
    at complete (/mnt/jenkins/workspace/happy-path-branch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:368:12)
    at QueueRunner.clearStack (/mnt/jenkins/workspace/happy-path-branch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:660:9)
    at QueueRunner.run (/mnt/jenkins/workspace/happy-path-branch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1881:12)
    at /mnt/jenkins/workspace/happy-path-branch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1898:16
    at /mnt/jenkins/workspace/happy-path-branch/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1842:9
    at /mnt/jenkins/workspace/happy-path-branch/node_modules/jasminewd2/index.js:16:5
    at ManagedPromise.invokeCallback_ (/mnt/jenkins/workspace/happy-path-branch/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/mnt/jenkins/workspace/happy-path-branch/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/mnt/jenkins/workspace/happy-path-branch/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/mnt/jenkins/workspace/happy-path-branch/node_modules/selenium-webdriver/lib/promise.js:2775:27)
    at /mnt/jenkins/workspace/happy-path-branch/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

still happening for me. Can you help here.
